// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeBt2RnEdImFiglSVFtvAD5CEnGZl3O0c',
    appId: '1:225270434812:android:805bc0edb402d5c9740079',
    messagingSenderId: '225270434812',
    projectId: 'workout-application1',
    databaseURL:
        'https://workout-application1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'workout-application1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_AtF0mTblhXwnXNzwEDP6BuStGqg93s',
    appId: '1:225270434812:ios:5f393bd45585be67740079',
    messagingSenderId: '225270434812',
    projectId: 'workout-application1',
    databaseURL:
        'https://workout-application1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'workout-application1.appspot.com',
    iosClientId:
        '225270434812-ivl5bgk4865kg0o74dnv2l5n1mhhg34n.apps.googleusercontent.com',
    iosBundleId: 'com.company.workou',
  );
}
